# Starter pipeline


jobs:
- job: 'radlab_semantic_search_engine_pipeline'
  pool:
    vmImage: 'ubuntu-22.04'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: pip install black
    displayName: 'Install dependencies (black)'

  - script: black . -t py39 -t py310 -t py311 --line-length=85
    continueOnError: true
    displayName: 'Run black . -t py39 -t py310 -t py311 --line-length=85'

  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: 'print(''FINISH'')'
  